[1,"Error occurred during cleanup: Error: The process cannot access the file because it is being used by another process. (os error 32): remove 'C:\\Users\\adels\\AppData\\Local\\Temp\\quarto-session29348efaf6eba3b8'\n"]
